version: '3.8'
services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - 3005:3005
    networks:
      - common-network
    # env_file:
    #   - dist/.env
  mysql-container:
    image: mysql
    volumes:
      - /Users/zdx/Dev/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: meeting_room_booking_system
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - common-network
  redis-container:
    image: redis
    volumes:
      - /Users/zdx/Dev/redisDB:/data
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
